//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PanelWork.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Istifadeci
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Istifadeci()
        {
            this.Sifaris = new HashSet<Sifari>();
        }
    
        public int user_id { get; set; }
        public string user_name { get; set; }
        public string user_surname { get; set; }
        public string user_password { get; set; }
        public string user_img { get; set; }
        public string user_salary { get; set; }
        public Nullable<System.DateTime> user_job_begin { get; set; }
        public string user_email { get; set; }
        public Nullable<int> user_rol_type { get; set; }
    
        public virtual Rol Rol { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sifari> Sifaris { get; set; }
    }
}
