//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PanelWork.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mehsul
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Mehsul()
        {
            this.Sifaris = new HashSet<Sifari>();
        }
    
        public int mehsul_id { get; set; }
        public string mehsulun_adi { get; set; }
        public string mehsulun_linki { get; set; }
        public string mehsulun_sekli { get; set; }
        public string mehsul_qiymeti { get; set; }
        public Nullable<int> mehsul_price { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sifari> Sifaris { get; set; }
    }
}
