//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PanelWork.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DB_A3E145_azmanazEntities : DbContext
    {
        public DB_A3E145_azmanazEntities()
            : base("name=DB_A3E145_azmanazEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Istifadeci> Istifadecis { get; set; }
        public virtual DbSet<Mehsul> Mehsuls { get; set; }
        public virtual DbSet<Rol> Rols { get; set; }
        public virtual DbSet<Sifari> Sifaris { get; set; }
        public virtual DbSet<SifarisNovu> SifarisNovus { get; set; }
    }
}
